Blog/urls.py
from django.conf.urls.static import static

from Blog import settings
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shokirov.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

shokirov/urls.py
from django.urls import path

from shokirov.views import HomePageView, UserRegisterView, UserLoginView, UserLogoutView, UserHomeView, UserAboutView, \
    UserPostDetailView, UserPostConfirmDeleteView, UserPostsView, UserPostsFormView, UserPostsTuriView, UserPostLarView

app_name = 'shokirov'
urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('about/', UserAboutView.as_view(), name='about'),
    path('home/', UserHomeView.as_view(), name='home'),
    path('post_detail/', UserPostDetailView.as_view(), name='post_detail'),
    path('post_confirm_delete/', UserPostConfirmDeleteView.as_view(), name='post_confirm_delete'),
    path('user_posts/', UserPostsView.as_view(), name='user_posts'),
    path('post_form/', UserPostsFormView.as_view(), name='post_form'),
    path('post_turi/', UserPostsTuriView.as_view(), name='post_turi'),
    path('postlar/', UserPostLarView.as_view(), name='postlar'),
]

shokirov/models.py
from django.contrib.auth.models import User
from django.db import models


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Profile(AbstractBaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_img = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    location = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def str(self):
        return self.user.username


class Post(AbstractBaseModel):
    title = models.CharField(max_length=128, default="title")
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="usercha")

    def str(self):
        return self.user

shokirov/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import CreateView

from shokirov.form import UserRegistrationModelForm, UserLoginForm, PostCreateForm
from shokirov.models import Profile, Post


class HomePageView(View):
    def get(self, request):
        return render(request, 'shokirov/home.html')


class UserRegisterView(View):
    def get(self, request):
        form = UserRegistrationModelForm()
        return render(request, "shokirov/register.html", {"form": form})

    def post(self, request):
        form = UserRegistrationModelForm(data=request.POST)
        if form.is_valid():
            messages.success(request, "User registered successfully")
            form.save()
            return redirect('shokirov:login')
        else:
            return render(request, "shokirov/register.html", {"form": form})


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, "shokirov/login.html", {"form": form})

    def post(self, request):
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                print(request.COOKIES)
                messages.success(request, "User logged in successfully")
                return redirect("shokirov:home-page")
            else:
                messages.error(request, "Username or password is wrong")
                return redirect("shokirov:login")
        else:
            return render(request, "shokirov/login.html", {"form": form})


class UserLogoutView(View):
    def get(self, request):
        return render(request, "shokirov/logout.html")

    def post(self, request):
        logout(request)
        messages.info(request, "User logged out successfully")
        return redirect('shokirov:home-page')


class UserAboutView(View):
    def get(self, request):
        return render(request, "shokirov/about.html")


class UserHomeView(View):
    def get(self, request):
        return render(request, "shokirov/home.html")


class UserPostDetailView(View):
    def get(self, request):
        return render(request, "shokirov/post_detail.html")


class UserPostConfirmDeleteView(View):
    def get(self, request):
        return render(request, "shokirov/post_confirm_delete.html")


class UserPostsView(View):
    def get(self, request):
        return render(request, "shokirov/user_posts.html")


class UserPostsFormView(View):
    def get(self, request):
        return render(request, "shokirov/post_form.html")


class UserPostLarView(View):
    def get(self, request):
        return render(request, "shokirov/user_posts.html")


class UserPostsTuriView(CreateView):
    model = Post
    form = PostCreateForm
    fields = ['title', 'content', 'user']
    template_name = "shokirov/post_form.html"

templates/shokirov/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'shokirov:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'shokirov:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'shokirov:about' %}">About</a>
            </div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:post_form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:user_posts' %}">Profile</a>


                    <a class="nav-item nav-link" href="{% url 'shokirov:logout' %}">Logout</a>

                {% else %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:register' %}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                <h1>About Page</h1>
                    <div class="container mt-5">
                        <h2>About Us</h2>
                        <p>Welcome to our Django Blog! This blog is dedicated to sharing knowledge, experiences, and thoughts on various topics.</p>

                        <h3>Our Mission</h3>
                        <p>Our mission is to provide valuable and insightful content to our readers. We aim to engage, educate, and entertain through our blog posts.</p>

                        <h3>Meet the Team</h3>
                        <p>We are a passionate team of writers, developers, and enthusiasts who love sharing our expertise with the world.</p>

                        <!-- Add more content about your team, mission, etc. -->

                        <p>Feel free to explore our blog and discover a wide range of articles covering different subjects.</p>
                    </div>

                </div>
                <div class="col-md-4">
                  <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                      </ul>
                    </p>
                  </div>
                </div>
              </div>
            </main>
        
            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        </body>
        </html>
        

templates/shokirov/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'shokirov:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'shokirov:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'shokirov:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
           {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:post_form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:user_posts' %}">Profile</a>


                    <a class="nav-item nav-link" href="{% url 'shokirov:logout' %}">Logout</a>

                {% else %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:register' %}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h3>Django messages might be shown here</h3>
              </div>
              <article class="media content-section">
                <img class="rounded-circle article-img" src="{% static 'corey.jpeg' %}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="user_posts.html">Jordan Gibbs</a>
                    <small class="text-muted">Feb 19, 2023</small>
                  </div>
                  <h2><a class="article-title" href="{% url 'shokirov:post_detail' %}">I have been watching a decade.</a></h2>
                </div>
              </article>
              <article class="media content-section">
                <img class="rounded-circle article-img" src="{% static 'gibbs.jpeg' %}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="user_posts.html">Jordan Gibbs </a>
                    <small class="text-muted">Feb 19, 2023</small>
                  </div>
                  <h5><a class="article-title" href="{% url 'shokirov:post_detail' %}">Do Gimmicky ChatGPT Prompts Actually Work?</a></h5>
                </div>
              </article>
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/shokirov/login.html
{% block title %} Login Page {% endblock %}
{% block body %}
    <h1>User Login Form</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}


    <button type="submit">Submit</button>

    </form>

{% endblock %}

templates/shokirov/logout.html
{% block title %} Log Out {% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        Are you sure to Log Out
            <a><button type="submit">Yes</button></a>

        </form>
        <a href="{% url 'shokirov:home-page' %}">
                    <button>No</button></a>
{% endblock %}

templates/shokirov/post_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'shokirov:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'shokirov:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'shokirov:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
              <div class="navbar-nav">
               {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:post_form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:user_posts' %}">Profile</a>


                    <a class="nav-item nav-link" href="{% url 'shokirov:logout' %}">Logout</a>

                {% else %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:register' %}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h3>
              </div>
                <div class="content-section">
                    <form method="POST">
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Delete Post</legend>
                            <h2>Are you sure you want to delete the post "I have been watching a decade."</h2>
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                            <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                  </ul>
                </p>
              </div>
            </div>
            </div>
            </main>
            
            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            </body>
            </html>
            
            

templates/shokirov/post_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'shokirov:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'shokirov:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'shokirov:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
                 <div class="navbar-nav">
              {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:post_form' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:user_posts' %}">Profile</a>


                    <a class="nav-item nav-link" href="{% url 'shokirov:logout' %}">Logout</a>

                {% else %}
                    <a class="nav-item nav-link" href="{% url 'shokirov:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'shokirov:register' %}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h3>Django messages might be shown here</h3>
              </div>
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{% static 'corey.jpeg' %}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="user_posts.html">RapidFork Technology</a>
        <small class="text-muted">Feb 19, 2023</small>
         <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="#">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'shokirov:post_confirm_delete' %}">Delete</a>
          </div>
        
      </div>
      <h2 class="article-title">I have been watching a decade.</h2>
      <p class="article-content">I have been watching a decade worth of The Ask Project
        by Corey Gil-Shuster on YouTube. Makes me have very little hope of there ever 
        being a two state solution. The Palestinians seem
        Makes me have very little hope of there ever 
        being a two state solution. The Palestinians seem
      </p>
    </div>
  </article>
</div>
<div class="col-md-4">
  <div class="content-section">
    <h3>Our Sidebar</h3>
    <p class='text-muted'>You can put any information here you'd like.
      <ul class="list-group">
        <li class="list-group-item list-group-item-light">Latest Posts</li>
        <li class="list-group-item list-group-item-light">Announcements</li>
        <li class="list-group-item list-group-item-light">Calendars</li>
        <li class="list-group-item list-group-item-light">etc</li>
      </ul>
    </p>
  </div>
</div>
</div>
</main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/shokirov/register.html
{% block title %} Register Page {% endblock %}
{% block body %}
    <h1> Registration Page</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Register</button>

    </form>

{% endblock %}